### ISSUE TITLE
[BUG] RESET PASSWORD SUCCESS BUT THERE'S NO MESSAGE

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#1]
[watch](https://www.dropbox.com/s/3wbhs8764dz4fho/WhatsApp%20Video%202019-05-15%20at%209.44.32%20AM.mp4?dl=0)

**Comment by budi7** [comment]
fixed at [1.0.4](https://github.com/budi7/Skytech-Ecommerce/releases)
