### ISSUE TITLE
[BUG] MY PREVIOUS TRANSACTION NOT DISPLAYING

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#2]
![query say data exists](https://user-images.githubusercontent.com/5895063/57745538-c116b000-76f7-11e9-8eaa-b7de4089b101.png)

![not showing in mobile apps](https://user-images.githubusercontent.com/5895063/57745752-8bbe9200-76f8-11e9-9f77-35946242b680.jpeg)

username : 089654562931
password : admin123

**Comment by budi7** [comment]
moved to #6
