### ISSUE TITLE
[QUESTION] HOW TO TEST FEATURE "SCAN KODE" ?

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#3]
![SCAN NOT WORKING ON PAPER](https://user-images.githubusercontent.com/5895063/57745986-8a419980-76f9-11e9-97a5-e5c0973075de.jpeg)

**Comment by budi7** [comment]
Just put you device camera towards the barcode. 
![ezgif-1-b31a64c0ea37](https://user-images.githubusercontent.com/10555410/57836263-86417480-77ea-11e9-8d9d-9154b3c5485f.gif)

Note:
Please confirm that your barcode readable, and have formatted in common format (such as  CODE_39, EAN_8, EAN_13)

**Comment by chelsymooy** [comment]
ada ketentuan lain?
seperti; size barcode, background color (noise), etc

**Comment by budi7** [comment]
Nope, as long as your barcodes are readable, and correctly formatted (CODE_39, EAN_8, EAN_13)
