### ISSUE TITLE
[FEATURE REQUEST] RE-FORMATTING EXPIRED DATE IN MY VOUCHER

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#4]
![WhatsApp Image 2019-05-15 at 10 29 28 AM](https://user-images.githubusercontent.com/5895063/57746699-8cf1be00-76fc-11e9-9e52-8d6399148834.jpeg)

**Comment by budi7** [comment]
fixed at [1.0.4](https://github.com/budi7/Skytech-Ecommerce/releases)
