### ISSUE TITLE
[BUG] MY GARANSI NOT DISPLAYING

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#5]
MENU DI MOBILE MY GARANSI
![WhatsApp Image 2019-05-16 at 10 20 03 AM](https://user-images.githubusercontent.com/5895063/57824145-49628700-77c4-11e9-8b0c-2809aeeb8a92.jpeg)

QUERY MY GARANSI
![image](https://user-images.githubusercontent.com/5895063/57824153-554e4900-77c4-11e9-905b-dab9648c42eb.png)

USER : 089654562932
PASS : admin123

**Comment by budi7** [comment]
moved to #6
