### ISSUE TITLE
[BUG] MY GARANSI NOT DISPLAYING THEN ERROR ARISE

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#8]
login dengan
USER : 089654562932
PASS : admin123

1. DI API ada garansi, tapi di apps "tidak ada"
![WhatsApp Image 2019-05-20 at 9 50 55 AM](https://user-images.githubusercontent.com/5895063/57993858-ef740100-7ae4-11e9-91ff-eaa7d1fbed18.jpeg)

2. saat logout lalu login lagi, muncul error ini
![WhatsApp Image 2019-05-20 at 9 50 55 AM (1)](https://user-images.githubusercontent.com/5895063/57993874-03b7fe00-7ae5-11e9-9ef4-c7faad220b70.jpeg)

3. kalau di klik view messages muncul ini
![WhatsApp Image 2019-05-20 at 9 50 55 AM (2)](https://user-images.githubusercontent.com/5895063/57993898-17636480-7ae5-11e9-9fc9-506917ea1d8b.jpeg)

**Comment by chelsymooy** [comment]
#5

**Comment by budi7** [comment]
Fixed [1.0.5](https://github.com/budi7/Skytech-Ecommerce/releases/tag/1.0.5)
