### ISSUE TITLE
[FEATURE REQUEST] DATE FORMAT IN TRANSACTION HISTORY UNREADABLE FOR COMMON USER

### ISSUE THREAD

**Issue by chelsymooy** [budi7/Skytech-Ecommerce#9]
![WhatsApp Image 2019-05-20 at 9 57 10 AM](https://user-images.githubusercontent.com/5895063/57994109-d28bfd80-7ae5-11e9-86df-38847625033f.jpeg)

**Comment by budi7** [comment]
fixed [1.0.5](https://github.com/budi7/Skytech-Ecommerce/releases/tag/1.0.5)
